package main

import (
	"fmt"
)

func main(){
	s:= "abc"
	t:= "abcd"
	fmt.Println(string(findTheDifference(s,t)))
}
/* String t is generated by random shuffling string s and
then add one more letter at a random position. */
func findTheDifference(s string, t string) byte {
	mm := make(map[byte]int)

	var result byte
	for i := range s {
		mm[s[i]] += 1
	}
	for i := range t {
		if value, ok := mm[t[i]]; ok && value >= 1 {
			continue
		}

		result = t[i]
	}

	return result
}


